import type { Sport } from '../types/news';

export const SPORTS: Sport[] = [
  {
    id: 'tennis',
    label: 'Tennis',
    query: 'tennis',
    icon: '🎾',
    color: '#4ade80',
    bgClass: 'bg-sport-tennis',
    textClass: 'text-sport-tennis',
    borderClass: 'border-sport-tennis',
  },
  {
    id: 'basketball',
    label: 'NBA Basketball',
    query: 'basketball NBA',
    icon: '🏀',
    color: '#f97316',
    bgClass: 'bg-sport-basketball',
    textClass: 'text-sport-basketball',
    borderClass: 'border-sport-basketball',
  },
  {
    id: 'cricket',
    label: 'Cricket',
    query: 'cricket IPL',
    icon: '🏏',
    color: '#3b82f6',
    bgClass: 'bg-sport-cricket',
    textClass: 'text-sport-cricket',
    borderClass: 'border-sport-cricket',
  },
  {
    id: 'soccer',
    label: 'Soccer',
    query: 'soccer',
    icon: '⚽',
    color: '#22c55e',
    bgClass: 'bg-sport-soccer',
    textClass: 'text-sport-soccer',
    borderClass: 'border-sport-soccer',
  },
  {
    id: 'nfl',
    label: 'NFL Football',
    query: 'nfl',
    icon: '🏈',
    color: '#8b5cf6',
    bgClass: 'bg-sport-nfl',
    textClass: 'text-sport-nfl',
    borderClass: 'border-sport-nfl',
  },
  {
    id: 'ncaa-basketball',
    label: 'College Basketball',
    query: 'ncaa-basketball',
    icon: '🏀',
    color: '#fbbf24',
    bgClass: 'bg-sport-ncaa-basketball',
    textClass: 'text-sport-ncaa-basketball',
    borderClass: 'border-sport-ncaa-basketball',
  },
  {
    id: 'formula1',
    label: 'Formula 1',
    query: 'formula1',
    icon: '🏎️',
    color: '#f43f5e',
    bgClass: 'bg-sport-formula1',
    textClass: 'text-sport-formula1',
    borderClass: 'border-sport-formula1',
  },
  {
    id: 'ncaa-football',
    label: 'College Football',
    query: 'ncaa-football',
    icon: '🏈',
    color: '#06b6d4',
    bgClass: 'bg-sport-ncaa-football',
    textClass: 'text-sport-ncaa-football',
    borderClass: 'border-sport-ncaa-football',
  },
];

export const SPORT_MAP = Object.fromEntries(SPORTS.map((s) => [s.id, s])) as Record<string, Sport>;
