import type { SportId, SportTeamConfig } from '../types/news';

export const SPORT_TEAMS: Partial<Record<SportId, SportTeamConfig>> = {
  tennis: {
    entityLabel: 'Players',
    teams: [
      { id: 'alcaraz', name: 'Carlos Alcaraz', searchTerm: 'Alcaraz' },
      { id: 'sinner', name: 'Jannik Sinner', searchTerm: 'Sinner' },
      { id: 'djokovic', name: 'Novak Djokovic', searchTerm: 'Djokovic' },
      { id: 'medvedev', name: 'Daniil Medvedev', searchTerm: 'Medvedev' },
      { id: 'zverev', name: 'Alexander Zverev', searchTerm: 'Zverev' },
      { id: 'rublev', name: 'Andrey Rublev', searchTerm: 'Rublev' },
      { id: 'swiatek', name: 'Iga Swiatek', searchTerm: 'Swiatek' },
      { id: 'sabalenka', name: 'Aryna Sabalenka', searchTerm: 'Sabalenka' },
      { id: 'gauff', name: 'Coco Gauff', searchTerm: 'Gauff' },
      { id: 'rybakina', name: 'Elena Rybakina', searchTerm: 'Rybakina' },
      { id: 'pegula', name: 'Jessica Pegula', searchTerm: 'Pegula' },
      { id: 'keys', name: 'Madison Keys', searchTerm: 'Madison Keys' },
    ],
  },

  basketball: {
    entityLabel: 'Teams',
    teams: [
      { id: 'celtics', name: 'Boston Celtics', searchTerm: 'Celtics' },
      { id: 'warriors', name: 'Golden State Warriors', searchTerm: 'Warriors' },
      { id: 'lakers', name: 'LA Lakers', searchTerm: 'Lakers' },
      { id: 'heat', name: 'Miami Heat', searchTerm: 'Heat' },
      { id: 'bucks', name: 'Milwaukee Bucks', searchTerm: 'Bucks' },
      { id: 'knicks', name: 'NY Knicks', searchTerm: 'Knicks' },
      { id: 'sixers', name: 'Philadelphia 76ers', searchTerm: '76ers' },
      { id: 'suns', name: 'Phoenix Suns', searchTerm: 'Suns' },
      { id: 'bulls', name: 'Chicago Bulls', searchTerm: 'Chicago Bulls' },
      { id: 'mavericks', name: 'Dallas Mavericks', searchTerm: 'Mavericks' },
      { id: 'nuggets', name: 'Denver Nuggets', searchTerm: 'Nuggets' },
      { id: 'grizzlies', name: 'Memphis Grizzlies', searchTerm: 'Grizzlies' },
      { id: 'thunder', name: 'OKC Thunder', searchTerm: 'Thunder' },
      { id: 'cavaliers', name: 'Cleveland Cavaliers', searchTerm: 'Cavaliers' },
      { id: 'clippers', name: 'LA Clippers', searchTerm: 'Clippers' },
      { id: 'nets', name: 'Brooklyn Nets', searchTerm: 'Nets' },
      { id: 'raptors', name: 'Toronto Raptors', searchTerm: 'Raptors' },
      { id: 'spurs', name: 'San Antonio Spurs', searchTerm: 'Spurs' },
      { id: 'hawks', name: 'Atlanta Hawks', searchTerm: 'Atlanta Hawks' },
      { id: 'pelicans', name: 'New Orleans Pelicans', searchTerm: 'Pelicans' },
    ],
  },

  cricket: {
    entityLabel: 'Teams',
    teams: [
      { id: 'india', name: 'India', searchTerm: 'India cricket' },
      { id: 'australia', name: 'Australia', searchTerm: 'Australia cricket' },
      { id: 'england', name: 'England', searchTerm: 'England cricket' },
      { id: 'pakistan', name: 'Pakistan', searchTerm: 'Pakistan cricket' },
      { id: 'nz', name: 'New Zealand', searchTerm: 'New Zealand cricket' },
      { id: 'sa', name: 'South Africa', searchTerm: 'South Africa cricket' },
      { id: 'wi', name: 'West Indies', searchTerm: 'West Indies cricket' },
      { id: 'mi', name: 'Mumbai Indians', searchTerm: 'Mumbai Indians' },
      { id: 'csk', name: 'Chennai Super Kings', searchTerm: 'Chennai Super Kings' },
      { id: 'rcb', name: 'Royal Challengers', searchTerm: 'Royal Challengers' },
      { id: 'kkr', name: 'Kolkata Knight Riders', searchTerm: 'Kolkata Knight Riders' },
      { id: 'dc', name: 'Delhi Capitals', searchTerm: 'Delhi Capitals' },
    ],
  },

  soccer: {
    entityLabel: 'Clubs',
    teams: [
      { id: 'arsenal', name: 'Arsenal', searchTerm: 'Arsenal' },
      { id: 'chelsea', name: 'Chelsea', searchTerm: 'Chelsea FC' },
      { id: 'liverpool', name: 'Liverpool', searchTerm: 'Liverpool FC' },
      { id: 'mancity', name: 'Manchester City', searchTerm: 'Manchester City' },
      { id: 'manutd', name: 'Manchester United', searchTerm: 'Manchester United' },
      { id: 'tottenham', name: 'Tottenham', searchTerm: 'Tottenham' },
      { id: 'realmadrid', name: 'Real Madrid', searchTerm: 'Real Madrid' },
      { id: 'barcelona', name: 'Barcelona', searchTerm: 'FC Barcelona' },
      { id: 'atletico', name: 'Atletico Madrid', searchTerm: 'Atletico Madrid' },
      { id: 'bayernmunich', name: 'Bayern Munich', searchTerm: 'Bayern Munich' },
      { id: 'dortmund', name: 'Borussia Dortmund', searchTerm: 'Borussia Dortmund' },
      { id: 'juventus', name: 'Juventus', searchTerm: 'Juventus' },
      { id: 'intermilan', name: 'Inter Milan', searchTerm: 'Inter Milan' },
      { id: 'acmilan', name: 'AC Milan', searchTerm: 'AC Milan' },
      { id: 'psg', name: 'Paris Saint-Germain', searchTerm: 'PSG' },
      { id: 'lagalaxy', name: 'LA Galaxy', searchTerm: 'LA Galaxy' },
    ],
  },

  nfl: {
    entityLabel: 'Teams',
    teams: [
      { id: 'patriots', name: 'New England Patriots', searchTerm: 'Patriots' },
      { id: 'cowboys', name: 'Dallas Cowboys', searchTerm: 'Cowboys' },
      { id: 'packers', name: 'Green Bay Packers', searchTerm: 'Packers' },
      { id: '49ers', name: 'San Francisco 49ers', searchTerm: '49ers' },
      { id: 'chiefs', name: 'Kansas City Chiefs', searchTerm: 'Chiefs' },
      { id: 'bills', name: 'Buffalo Bills', searchTerm: 'Bills' },
      { id: 'eagles', name: 'Philadelphia Eagles', searchTerm: 'Eagles' },
      { id: 'ravens', name: 'Baltimore Ravens', searchTerm: 'Ravens' },
      { id: 'giants', name: 'New York Giants', searchTerm: 'Giants' },
      { id: 'bears', name: 'Chicago Bears', searchTerm: 'Chicago Bears' },
      { id: 'rams', name: 'LA Rams', searchTerm: 'Rams' },
      { id: 'seahawks', name: 'Seattle Seahawks', searchTerm: 'Seahawks' },
      { id: 'raiders', name: 'Las Vegas Raiders', searchTerm: 'Raiders' },
      { id: 'steelers', name: 'Pittsburgh Steelers', searchTerm: 'Steelers' },
      { id: 'bengals', name: 'Cincinnati Bengals', searchTerm: 'Bengals' },
      { id: 'dolphins', name: 'Miami Dolphins', searchTerm: 'Dolphins' },
      { id: 'broncos', name: 'Denver Broncos', searchTerm: 'Broncos' },
      { id: 'vikings', name: 'Minnesota Vikings', searchTerm: 'Vikings' },
    ],
  },

  'ncaa-basketball': {
    entityLabel: 'Programs',
    teams: [
      { id: 'duke', name: 'Duke', searchTerm: 'Duke basketball' },
      { id: 'kentucky', name: 'Kentucky', searchTerm: 'Kentucky basketball' },
      { id: 'kansas', name: 'Kansas', searchTerm: 'Kansas basketball' },
      { id: 'unc', name: 'North Carolina', searchTerm: 'North Carolina basketball' },
      { id: 'gonzaga', name: 'Gonzaga', searchTerm: 'Gonzaga' },
      { id: 'uconn', name: 'UConn', searchTerm: 'UConn basketball' },
      { id: 'michiganstate', name: 'Michigan State', searchTerm: 'Michigan State basketball' },
      { id: 'arizona', name: 'Arizona', searchTerm: 'Arizona basketball' },
      { id: 'villanova', name: 'Villanova', searchTerm: 'Villanova' },
      { id: 'indiana', name: 'Indiana', searchTerm: 'Indiana basketball' },
      { id: 'ucla', name: 'UCLA', searchTerm: 'UCLA basketball' },
      { id: 'houston', name: 'Houston', searchTerm: 'Houston Cougars' },
    ],
  },

  formula1: {
    entityLabel: 'Drivers & Teams',
    teams: [
      { id: 'verstappen', name: 'Max Verstappen', searchTerm: 'Verstappen' },
      { id: 'hamilton', name: 'Lewis Hamilton', searchTerm: 'Hamilton' },
      { id: 'leclerc', name: 'Charles Leclerc', searchTerm: 'Leclerc' },
      { id: 'norris', name: 'Lando Norris', searchTerm: 'Norris' },
      { id: 'sainz', name: 'Carlos Sainz', searchTerm: 'Sainz' },
      { id: 'alonso', name: 'Fernando Alonso', searchTerm: 'Alonso' },
      { id: 'russell', name: 'George Russell', searchTerm: 'George Russell' },
      { id: 'perez', name: 'Sergio Perez', searchTerm: 'Perez' },
      { id: 'redbull', name: 'Red Bull Racing', searchTerm: 'Red Bull Racing' },
      { id: 'mercedes', name: 'Mercedes', searchTerm: 'Mercedes F1' },
      { id: 'ferrari', name: 'Ferrari', searchTerm: 'Ferrari F1' },
      { id: 'mclaren', name: 'McLaren', searchTerm: 'McLaren F1' },
      { id: 'astonmartin', name: 'Aston Martin', searchTerm: 'Aston Martin F1' },
      { id: 'alpine', name: 'Alpine', searchTerm: 'Alpine F1' },
    ],
  },

  'ncaa-football': {
    entityLabel: 'Programs',
    teams: [
      { id: 'alabama', name: 'Alabama', searchTerm: 'Alabama football' },
      { id: 'ohiostate', name: 'Ohio State', searchTerm: 'Ohio State football' },
      { id: 'georgia', name: 'Georgia', searchTerm: 'Georgia Bulldogs' },
      { id: 'michigan', name: 'Michigan', searchTerm: 'Michigan football' },
      { id: 'clemson', name: 'Clemson', searchTerm: 'Clemson' },
      { id: 'lsu', name: 'LSU', searchTerm: 'LSU football' },
      { id: 'oklahoma', name: 'Oklahoma', searchTerm: 'Oklahoma Sooners' },
      { id: 'notredame', name: 'Notre Dame', searchTerm: 'Notre Dame football' },
      { id: 'pennstate', name: 'Penn State', searchTerm: 'Penn State football' },
      { id: 'usc', name: 'USC', searchTerm: 'USC football' },
      { id: 'texas', name: 'Texas', searchTerm: 'Texas Longhorns' },
      { id: 'florida', name: 'Florida', searchTerm: 'Florida Gators' },
    ],
  },
};
