import type { SportId, SportTeamConfig } from '../types/news';

export const SPORT_TEAMS: Partial<Record<SportId, SportTeamConfig>> = {
  tennis: {
    groups: [
      {
        label: "Men's ATP",
        items: [
          { id: 'alcaraz',    name: 'Carlos Alcaraz',        searchTerm: 'Alcaraz' },
          { id: 'sinner',     name: 'Jannik Sinner',         searchTerm: 'Sinner' },
          { id: 'djokovic',   name: 'Novak Djokovic',        searchTerm: 'Djokovic' },
          { id: 'medvedev',   name: 'Daniil Medvedev',       searchTerm: 'Medvedev' },
          { id: 'zverev',     name: 'Alexander Zverev',      searchTerm: 'Zverev' },
          { id: 'rublev',     name: 'Andrey Rublev',         searchTerm: 'Rublev' },
          { id: 'rune',       name: 'Holger Rune',           searchTerm: 'Holger Rune' },
          { id: 'ruud',       name: 'Casper Ruud',           searchTerm: 'Casper Ruud' },
          { id: 'dimitrov',   name: 'Grigor Dimitrov',       searchTerm: 'Grigor Dimitrov' },
          { id: 'deminaur',   name: 'Alex de Minaur',        searchTerm: 'de Minaur' },
          { id: 'fritz',      name: 'Taylor Fritz',          searchTerm: 'Taylor Fritz' },
          { id: 'shelton',    name: 'Ben Shelton',           searchTerm: 'Ben Shelton' },
          { id: 'tiafoe',     name: 'Frances Tiafoe',        searchTerm: 'Frances Tiafoe' },
          { id: 'tsitsipas',  name: 'Stefanos Tsitsipas',   searchTerm: 'Tsitsipas' },
          { id: 'hurkacz',    name: 'Hubert Hurkacz',        searchTerm: 'Hubert Hurkacz' },
          { id: 'korda',      name: 'Sebastian Korda',       searchTerm: 'Sebastian Korda' },
          { id: 'tpaul',      name: 'Tommy Paul',            searchTerm: 'Tommy Paul' },
          { id: 'musetti',    name: 'Lorenzo Musetti',       searchTerm: 'Lorenzo Musetti' },
          { id: 'khachanov',  name: 'Karen Khachanov',       searchTerm: 'Karen Khachanov' },
          { id: 'humbert',    name: 'Ugo Humbert',           searchTerm: 'Ugo Humbert' },
          { id: 'draper',     name: 'Jack Draper',           searchTerm: 'Jack Draper' },
          { id: 'fils',       name: 'Arthur Fils',           searchTerm: 'Arthur Fils' },
          { id: 'faa',        name: 'Felix Auger-Aliassime', searchTerm: 'Auger-Aliassime' },
          { id: 'shapovalov', name: 'Denis Shapovalov',      searchTerm: 'Denis Shapovalov' },
          { id: 'jarry',      name: 'Nicolas Jarry',         searchTerm: 'Nicolas Jarry' },
        ],
      },
      {
        label: "Women's WTA",
        items: [
          { id: 'swiatek',    name: 'Iga Swiatek',           searchTerm: 'Swiatek' },
          { id: 'sabalenka',  name: 'Aryna Sabalenka',       searchTerm: 'Sabalenka' },
          { id: 'gauff',      name: 'Coco Gauff',            searchTerm: 'Gauff' },
          { id: 'rybakina',   name: 'Elena Rybakina',        searchTerm: 'Rybakina' },
          { id: 'pegula',     name: 'Jessica Pegula',        searchTerm: 'Pegula' },
          { id: 'keys',       name: 'Madison Keys',          searchTerm: 'Madison Keys' },
          { id: 'navarro',    name: 'Emma Navarro',          searchTerm: 'Emma Navarro' },
          { id: 'paolini',    name: 'Jasmine Paolini',       searchTerm: 'Jasmine Paolini' },
          { id: 'krejcikova', name: 'Barbora Krejcikova',    searchTerm: 'Krejcikova' },
          { id: 'kasatkina',  name: 'Daria Kasatkina',       searchTerm: 'Daria Kasatkina' },
          { id: 'kalinskaya', name: 'Anna Kalinskaya',       searchTerm: 'Anna Kalinskaya' },
          { id: 'andreeva',   name: 'Mirra Andreeva',        searchTerm: 'Mirra Andreeva' },
          { id: 'sakkari',    name: 'Maria Sakkari',         searchTerm: 'Maria Sakkari' },
          { id: 'svitolina',  name: 'Elina Svitolina',       searchTerm: 'Elina Svitolina' },
          { id: 'osaka',      name: 'Naomi Osaka',           searchTerm: 'Naomi Osaka' },
          { id: 'haddad',     name: 'Beatriz Haddad Maia',  searchTerm: 'Beatriz Haddad Maia' },
          { id: 'cgarcia',    name: 'Caroline Garcia',       searchTerm: 'Caroline Garcia' },
          { id: 'samsonova',  name: 'Liudmila Samsonova',   searchTerm: 'Liudmila Samsonova' },
          { id: 'azarenka',   name: 'Victoria Azarenka',    searchTerm: 'Victoria Azarenka' },
          { id: 'badosa',     name: 'Paula Badosa',          searchTerm: 'Paula Badosa' },
          { id: 'collins',    name: 'Danielle Collins',      searchTerm: 'Danielle Collins' },
          { id: 'fernandez',  name: 'Leylah Fernandez',     searchTerm: 'Leylah Fernandez' },
          { id: 'raducanu',   name: 'Emma Raducanu',         searchTerm: 'Emma Raducanu' },
          { id: 'stephens',   name: 'Sloane Stephens',       searchTerm: 'Sloane Stephens' },
          { id: 'kvitova',    name: 'Petra Kvitova',         searchTerm: 'Petra Kvitova' },
        ],
      },
    ],
  },

  basketball: {
    groups: [
      {
        label: 'Teams',
        items: [
          { id: 'celtics',    name: 'Boston Celtics',        searchTerm: 'Celtics' },
          { id: 'warriors',   name: 'Golden State Warriors', searchTerm: 'Warriors' },
          { id: 'lakers',     name: 'LA Lakers',             searchTerm: 'Lakers' },
          { id: 'heat',       name: 'Miami Heat',            searchTerm: 'Heat' },
          { id: 'bucks',      name: 'Milwaukee Bucks',       searchTerm: 'Bucks' },
          { id: 'knicks',     name: 'NY Knicks',             searchTerm: 'Knicks' },
          { id: 'sixers',     name: 'Philadelphia 76ers',    searchTerm: '76ers' },
          { id: 'suns',       name: 'Phoenix Suns',          searchTerm: 'Suns' },
          { id: 'bulls',      name: 'Chicago Bulls',         searchTerm: 'Chicago Bulls' },
          { id: 'mavericks',  name: 'Dallas Mavericks',      searchTerm: 'Mavericks' },
          { id: 'nuggets',    name: 'Denver Nuggets',        searchTerm: 'Nuggets' },
          { id: 'grizzlies',  name: 'Memphis Grizzlies',     searchTerm: 'Grizzlies' },
          { id: 'thunder',    name: 'OKC Thunder',           searchTerm: 'Thunder' },
          { id: 'cavaliers',  name: 'Cleveland Cavaliers',   searchTerm: 'Cavaliers' },
          { id: 'clippers',   name: 'LA Clippers',           searchTerm: 'Clippers' },
          { id: 'nets',       name: 'Brooklyn Nets',         searchTerm: 'Nets' },
          { id: 'raptors',    name: 'Toronto Raptors',       searchTerm: 'Raptors' },
          { id: 'spurs',      name: 'San Antonio Spurs',     searchTerm: 'Spurs' },
          { id: 'hawks',      name: 'Atlanta Hawks',         searchTerm: 'Atlanta Hawks' },
          { id: 'pelicans',   name: 'New Orleans Pelicans',  searchTerm: 'Pelicans' },
          { id: 'timberwolves', name: 'Minnesota Timberwolves', searchTerm: 'Timberwolves' },
          { id: 'rockets',    name: 'Houston Rockets',       searchTerm: 'Houston Rockets' },
          { id: 'pacers',     name: 'Indiana Pacers',        searchTerm: 'Indiana Pacers' },
          { id: 'magic',      name: 'Orlando Magic',         searchTerm: 'Orlando Magic' },
        ],
      },
      {
        label: 'Players',
        items: [
          { id: 'lebron',       name: 'LeBron James',              searchTerm: 'LeBron James' },
          { id: 'curry',        name: 'Stephen Curry',             searchTerm: 'Stephen Curry' },
          { id: 'giannis',      name: 'Giannis Antetokounmpo',     searchTerm: 'Giannis' },
          { id: 'jokic',        name: 'Nikola Jokic',              searchTerm: 'Jokic' },
          { id: 'luka',         name: 'Luka Doncic',               searchTerm: 'Luka Doncic' },
          { id: 'tatum',        name: 'Jayson Tatum',              searchTerm: 'Jayson Tatum' },
          { id: 'durant',       name: 'Kevin Durant',              searchTerm: 'Kevin Durant' },
          { id: 'embiid',       name: 'Joel Embiid',               searchTerm: 'Embiid' },
          { id: 'morant',       name: 'Ja Morant',                 searchTerm: 'Ja Morant' },
          { id: 'sga',          name: 'Shai Gilgeous-Alexander',   searchTerm: 'Shai Gilgeous-Alexander' },
          { id: 'booker',       name: 'Devin Booker',              searchTerm: 'Devin Booker' },
          { id: 'lillard',      name: 'Damian Lillard',            searchTerm: 'Lillard' },
          { id: 'adavis',       name: 'Anthony Davis',             searchTerm: 'Anthony Davis' },
          { id: 'kyrie',        name: 'Kyrie Irving',              searchTerm: 'Kyrie Irving' },
          { id: 'butler',       name: 'Jimmy Butler',              searchTerm: 'Jimmy Butler' },
          { id: 'ant',          name: 'Anthony Edwards',           searchTerm: 'Anthony Edwards' },
          { id: 'wemby',        name: 'Victor Wembanyama',         searchTerm: 'Wembanyama' },
          { id: 'haliburton',   name: 'Tyrese Haliburton',         searchTerm: 'Tyrese Haliburton' },
          { id: 'brunson',      name: 'Jalen Brunson',             searchTerm: 'Jalen Brunson' },
          { id: 'maxey',        name: 'Tyrese Maxey',              searchTerm: 'Tyrese Maxey' },
          { id: 'banchero',     name: 'Paolo Banchero',            searchTerm: 'Paolo Banchero' },
          { id: 'cunningham',   name: 'Cade Cunningham',           searchTerm: 'Cade Cunningham' },
          { id: 'dmitchell',    name: 'Donovan Mitchell',          searchTerm: 'Donovan Mitchell' },
          { id: 'trae',         name: 'Trae Young',                searchTerm: 'Trae Young' },
          { id: 'zion',         name: 'Zion Williamson',           searchTerm: 'Zion Williamson' },
          { id: 'defox',        name: "De'Aaron Fox",              searchTerm: "De'Aaron Fox" },
          { id: 'kat',          name: 'Karl-Anthony Towns',        searchTerm: 'Karl-Anthony Towns' },
          { id: 'jaylen',       name: 'Jaylen Brown',              searchTerm: 'Jaylen Brown' },
          { id: 'adebayo',      name: 'Bam Adebayo',              searchTerm: 'Bam Adebayo' },
          { id: 'draymond',     name: 'Draymond Green',            searchTerm: 'Draymond Green' },
          { id: 'klay',         name: 'Klay Thompson',             searchTerm: 'Klay Thompson' },
          { id: 'harden',       name: 'James Harden',              searchTerm: 'James Harden' },
          { id: 'siakam',       name: 'Pascal Siakam',             searchTerm: 'Pascal Siakam' },
          { id: 'fwagner',      name: 'Franz Wagner',              searchTerm: 'Franz Wagner' },
          { id: 'barnes',       name: 'Scottie Barnes',            searchTerm: 'Scottie Barnes' },
          { id: 'jjr',          name: 'Jaren Jackson Jr.',         searchTerm: 'Jaren Jackson Jr' },
          { id: 'mikal',        name: 'Mikal Bridges',             searchTerm: 'Mikal Bridges' },
          { id: 'anunoby',      name: 'OG Anunoby',                searchTerm: 'OG Anunoby' },
          { id: 'reaves',       name: 'Austin Reaves',             searchTerm: 'Austin Reaves' },
          { id: 'sengun',       name: 'Alperen Sengun',            searchTerm: 'Alperen Sengun' },
          { id: 'jgreen',       name: 'Jalen Green',               searchTerm: 'Jalen Green' },
          { id: 'mobley',       name: 'Evan Mobley',               searchTerm: 'Evan Mobley' },
          { id: 'dgarland',     name: 'Darius Garland',            searchTerm: 'Darius Garland' },
          { id: 'ingram',       name: 'Brandon Ingram',            searchTerm: 'Brandon Ingram' },
          { id: 'wiggins',      name: 'Andrew Wiggins',            searchTerm: 'Andrew Wiggins' },
          { id: 'middleton',    name: 'Khris Middleton',           searchTerm: 'Khris Middleton' },
          { id: 'chris',        name: 'Chris Paul',                searchTerm: 'Chris Paul' },
          { id: 'ibaka',        name: 'Josh Giddey',               searchTerm: 'Josh Giddey' },
          { id: 'lamelo',       name: 'LaMelo Ball',               searchTerm: 'LaMelo Ball' },
          { id: 'jmurray',      name: 'Jamal Murray',              searchTerm: 'Jamal Murray' },
        ],
      },
    ],
  },

  soccer: {
    groups: [
      {
        label: 'Clubs',
        items: [
          { id: 'arsenal',      name: 'Arsenal',              searchTerm: 'Arsenal' },
          { id: 'chelsea',      name: 'Chelsea',              searchTerm: 'Chelsea FC' },
          { id: 'liverpool',    name: 'Liverpool',            searchTerm: 'Liverpool FC' },
          { id: 'mancity',      name: 'Manchester City',      searchTerm: 'Manchester City' },
          { id: 'manutd',       name: 'Manchester United',    searchTerm: 'Manchester United' },
          { id: 'tottenham',    name: 'Tottenham',            searchTerm: 'Tottenham' },
          { id: 'realmadrid',   name: 'Real Madrid',          searchTerm: 'Real Madrid' },
          { id: 'barcelona',    name: 'Barcelona',            searchTerm: 'FC Barcelona' },
          { id: 'atletico',     name: 'Atletico Madrid',      searchTerm: 'Atletico Madrid' },
          { id: 'bayernmunich', name: 'Bayern Munich',        searchTerm: 'Bayern Munich' },
          { id: 'dortmund',     name: 'Borussia Dortmund',   searchTerm: 'Borussia Dortmund' },
          { id: 'juventus',     name: 'Juventus',             searchTerm: 'Juventus' },
          { id: 'intermilan',   name: 'Inter Milan',          searchTerm: 'Inter Milan' },
          { id: 'acmilan',      name: 'AC Milan',             searchTerm: 'AC Milan' },
          { id: 'psg',          name: 'Paris Saint-Germain',  searchTerm: 'PSG' },
          { id: 'lagalaxy',     name: 'LA Galaxy',            searchTerm: 'LA Galaxy' },
          { id: 'napoli',       name: 'Napoli',               searchTerm: 'Napoli' },
          { id: 'porto',        name: 'Porto',                searchTerm: 'Porto FC' },
          { id: 'benfica',      name: 'Benfica',              searchTerm: 'Benfica' },
          { id: 'ajax',         name: 'Ajax',                 searchTerm: 'Ajax' },
        ],
      },
      {
        label: 'Players',
        items: [
          { id: 'messi',        name: 'Lionel Messi',         searchTerm: 'Messi' },
          { id: 'ronaldo',      name: 'Cristiano Ronaldo',    searchTerm: 'Cristiano Ronaldo' },
          { id: 'mbappe',       name: 'Kylian Mbappe',        searchTerm: 'Mbappe' },
          { id: 'haaland',      name: 'Erling Haaland',       searchTerm: 'Haaland' },
          { id: 'vinicius',     name: 'Vinicius Jr',          searchTerm: 'Vinicius' },
          { id: 'salah',        name: 'Mohamed Salah',        searchTerm: 'Mohamed Salah' },
          { id: 'bellingham',   name: 'Jude Bellingham',      searchTerm: 'Bellingham' },
          { id: 'debruyne',     name: 'Kevin De Bruyne',      searchTerm: 'De Bruyne' },
          { id: 'lewandowski',  name: 'Robert Lewandowski',   searchTerm: 'Lewandowski' },
          { id: 'kane',         name: 'Harry Kane',           searchTerm: 'Harry Kane' },
          { id: 'pedri',        name: 'Pedri',                searchTerm: 'Pedri' },
          { id: 'son',          name: 'Son Heung-min',        searchTerm: 'Son Heung-min' },
          { id: 'yamal',        name: 'Lamine Yamal',         searchTerm: 'Lamine Yamal' },
          { id: 'rodri',        name: 'Rodri',                searchTerm: 'Rodri' },
          { id: 'saka',         name: 'Bukayo Saka',          searchTerm: 'Bukayo Saka' },
          { id: 'foden',        name: 'Phil Foden',           searchTerm: 'Phil Foden' },
          { id: 'bruno',        name: 'Bruno Fernandes',      searchTerm: 'Bruno Fernandes' },
          { id: 'rodrygo',      name: 'Rodrygo',              searchTerm: 'Rodrygo' },
          { id: 'valverde',     name: 'Federico Valverde',    searchTerm: 'Federico Valverde' },
          { id: 'vvd',          name: 'Virgil van Dijk',      searchTerm: 'Virgil van Dijk' },
          { id: 'courtois',     name: 'Thibaut Courtois',     searchTerm: 'Thibaut Courtois' },
          { id: 'griezmann',    name: 'Antoine Griezmann',    searchTerm: 'Antoine Griezmann' },
          { id: 'neymar',       name: 'Neymar Jr',            searchTerm: 'Neymar' },
          { id: 'osimhen',      name: 'Victor Osimhen',       searchTerm: 'Victor Osimhen' },
          { id: 'kvaratskhelia', name: 'Khvicha Kvaratskhelia', searchTerm: 'Kvaratskhelia' },
          { id: 'lautaro',      name: 'Lautaro Martinez',     searchTerm: 'Lautaro Martinez' },
          { id: 'rashford',     name: 'Marcus Rashford',      searchTerm: 'Marcus Rashford' },
          { id: 'rdias',        name: 'Ruben Dias',           searchTerm: 'Ruben Dias' },
          { id: 'alisson',      name: 'Alisson Becker',       searchTerm: 'Alisson Becker' },
          { id: 'declan',       name: 'Declan Rice',          searchTerm: 'Declan Rice' },
          { id: 'leao',         name: 'Rafael Leao',          searchTerm: 'Rafael Leao' },
          { id: 'barella',      name: 'Nicolo Barella',       searchTerm: 'Nicolo Barella' },
          { id: 'garnacho',     name: 'Alejandro Garnacho',   searchTerm: 'Alejandro Garnacho' },
          { id: 'diaz',         name: 'Luis Diaz',            searchTerm: 'Luis Diaz soccer' },
          { id: 'nunez',        name: 'Darwin Nunez',         searchTerm: 'Darwin Nunez' },
          { id: 'pulisic',      name: 'Christian Pulisic',    searchTerm: 'Christian Pulisic' },
          { id: 'reece',        name: 'Reece James',          searchTerm: 'Reece James' },
          { id: 'thiago',       name: 'Thiago Silva',         searchTerm: 'Thiago Silva' },
          { id: 'bonmati',      name: 'Aitana Bonmati',       searchTerm: 'Aitana Bonmati' },
          { id: 'samkerr',      name: 'Sam Kerr',             searchTerm: 'Sam Kerr' },
          { id: 'putellas',     name: 'Alexia Putellas',      searchTerm: 'Alexia Putellas' },
          { id: 'trindad',      name: 'Trinity Rodman',       searchTerm: 'Trinity Rodman' },
          { id: 'sophiasmith',  name: 'Sophia Smith',         searchTerm: 'Sophia Smith soccer' },
          { id: 'alexmorgan',   name: 'Alex Morgan',          searchTerm: 'Alex Morgan' },
          { id: 'malloryswanson', name: 'Mallory Swanson',   searchTerm: 'Mallory Swanson' },
          { id: 'roselavelle',  name: 'Rose Lavelle',         searchTerm: 'Rose Lavelle' },
          { id: 'lindseyhoran', name: 'Lindsey Horan',        searchTerm: 'Lindsey Horan' },
          { id: 'hegerberg',    name: 'Ada Hegerberg',        searchTerm: 'Ada Hegerberg' },
          { id: 'wiegman',      name: 'Lauren Hemp',          searchTerm: 'Lauren Hemp' },
          { id: 'bronze',       name: 'Lucy Bronze',          searchTerm: 'Lucy Bronze' },
        ],
      },
    ],
  },

  nfl: {
    groups: [
      {
        label: 'Teams',
        items: [
          { id: 'patriots',   name: 'New England Patriots',  searchTerm: 'Patriots' },
          { id: 'cowboys',    name: 'Dallas Cowboys',        searchTerm: 'Cowboys' },
          { id: 'packers',    name: 'Green Bay Packers',     searchTerm: 'Packers' },
          { id: '49ers',      name: 'San Francisco 49ers',   searchTerm: '49ers' },
          { id: 'chiefs',     name: 'Kansas City Chiefs',    searchTerm: 'Chiefs' },
          { id: 'bills',      name: 'Buffalo Bills',         searchTerm: 'Buffalo Bills' },
          { id: 'eagles',     name: 'Philadelphia Eagles',   searchTerm: 'Eagles' },
          { id: 'ravens',     name: 'Baltimore Ravens',      searchTerm: 'Ravens' },
          { id: 'giants',     name: 'New York Giants',       searchTerm: 'NY Giants' },
          { id: 'bears',      name: 'Chicago Bears',         searchTerm: 'Chicago Bears' },
          { id: 'rams',       name: 'LA Rams',               searchTerm: 'LA Rams' },
          { id: 'seahawks',   name: 'Seattle Seahawks',      searchTerm: 'Seahawks' },
          { id: 'raiders',    name: 'Las Vegas Raiders',     searchTerm: 'Raiders' },
          { id: 'steelers',   name: 'Pittsburgh Steelers',   searchTerm: 'Steelers' },
          { id: 'bengals',    name: 'Cincinnati Bengals',    searchTerm: 'Bengals' },
          { id: 'dolphins',   name: 'Miami Dolphins',        searchTerm: 'Dolphins' },
          { id: 'broncos',    name: 'Denver Broncos',        searchTerm: 'Broncos' },
          { id: 'vikings',    name: 'Minnesota Vikings',     searchTerm: 'Vikings' },
          { id: 'texans',     name: 'Houston Texans',        searchTerm: 'Houston Texans' },
          { id: 'lions',      name: 'Detroit Lions',         searchTerm: 'Detroit Lions' },
          { id: 'colts',      name: 'Indianapolis Colts',    searchTerm: 'Indianapolis Colts' },
          { id: 'jets',       name: 'New York Jets',         searchTerm: 'NY Jets' },
        ],
      },
      {
        label: 'Players',
        items: [
          { id: 'mahomes',      name: 'Patrick Mahomes',      searchTerm: 'Mahomes' },
          { id: 'joshallan',    name: 'Josh Allen',            searchTerm: 'Josh Allen' },
          { id: 'lamar',        name: 'Lamar Jackson',         searchTerm: 'Lamar Jackson' },
          { id: 'hurts',        name: 'Jalen Hurts',           searchTerm: 'Jalen Hurts' },
          { id: 'burrow',       name: 'Joe Burrow',            searchTerm: 'Joe Burrow' },
          { id: 'stroud',       name: 'C.J. Stroud',           searchTerm: 'CJ Stroud' },
          { id: 'jefferson',    name: 'Justin Jefferson',       searchTerm: 'Justin Jefferson' },
          { id: 'tyreek',       name: 'Tyreek Hill',           searchTerm: 'Tyreek Hill' },
          { id: 'kelce',        name: 'Travis Kelce',          searchTerm: 'Travis Kelce' },
          { id: 'barkley',      name: 'Saquon Barkley',        searchTerm: 'Saquon Barkley' },
          { id: 'chase',        name: "Ja'Marr Chase",         searchTerm: 'Jamarr Chase' },
          { id: 'purdy',        name: 'Brock Purdy',           searchTerm: 'Brock Purdy' },
          { id: 'ceedeelamb',   name: 'CeeDee Lamb',           searchTerm: 'CeeDee Lamb' },
          { id: 'dkmetcalf',    name: 'DK Metcalf',            searchTerm: 'DK Metcalf' },
          { id: 'mccaffrey',    name: 'Christian McCaffrey',   searchTerm: 'Christian McCaffrey' },
          { id: 'henry',        name: 'Derrick Henry',         searchTerm: 'Derrick Henry' },
          { id: 'waddle',       name: 'Jaylen Waddle',         searchTerm: 'Jaylen Waddle' },
          { id: 'higgins',      name: 'Tee Higgins',           searchTerm: 'Tee Higgins' },
          { id: 'kittle',       name: 'George Kittle',         searchTerm: 'George Kittle' },
          { id: 'andrews',      name: 'Mark Andrews',          searchTerm: 'Mark Andrews' },
          { id: 'tjwatt',       name: 'T.J. Watt',             searchTerm: 'TJ Watt' },
          { id: 'parsons',      name: 'Micah Parsons',         searchTerm: 'Micah Parsons' },
          { id: 'nickbosa',     name: 'Nick Bosa',             searchTerm: 'Nick Bosa' },
          { id: 'mgarrett',     name: 'Myles Garrett',         searchTerm: 'Myles Garrett' },
          { id: 'maxxcrosby',   name: 'Maxx Crosby',           searchTerm: 'Maxx Crosby' },
          { id: 'hutchinson',   name: 'Aidan Hutchinson',      searchTerm: 'Aidan Hutchinson' },
          { id: 'evansmike',    name: 'Mike Evans',            searchTerm: 'Mike Evans' },
          { id: 'davante',      name: 'Davante Adams',         searchTerm: 'Davante Adams' },
          { id: 'jjsmith',      name: 'DeVonta Smith',         searchTerm: 'DeVonta Smith' },
          { id: 'stbrown',      name: "Amon-Ra St. Brown",     searchTerm: "Amon-Ra St Brown" },
          { id: 'jachobbs',     name: 'Josh Jacobs',           searchTerm: 'Josh Jacobs' },
          { id: 'pollard',      name: 'Tony Pollard',          searchTerm: 'Tony Pollard' },
          { id: 'laporte',      name: 'Sam LaPorta',           searchTerm: 'Sam LaPorta' },
          { id: 'lockett',      name: 'Tyler Lockett',         searchTerm: 'Tyler Lockett' },
          { id: 'jalenramsey',  name: 'Jalen Ramsey',          searchTerm: 'Jalen Ramsey' },
          { id: 'marshon',      name: 'Marshon Lattimore',     searchTerm: 'Marshon Lattimore' },
          { id: 'devito',       name: 'Tommy DeVito',          searchTerm: 'Tommy DeVito' },
          { id: 'pickett',      name: 'Kenny Pickett',         searchTerm: 'Kenny Pickett' },
          { id: 'fields',       name: 'Justin Fields',         searchTerm: 'Justin Fields' },
          { id: 'levis',        name: 'Will Levis',            searchTerm: 'Will Levis' },
          { id: 'florencepugh', name: 'Anthony Richardson',    searchTerm: 'Anthony Richardson quarterback' },
          { id: 'brockman',     name: 'Romeo Doubs',           searchTerm: 'Romeo Doubs' },
        ],
      },
    ],
  },

  formula1: {
    groups: [
      {
        label: 'Drivers',
        items: [
          { id: 'verstappen',  name: 'Max Verstappen',      searchTerm: 'Verstappen' },
          { id: 'hamilton',    name: 'Lewis Hamilton',      searchTerm: 'Lewis Hamilton' },
          { id: 'leclerc',     name: 'Charles Leclerc',     searchTerm: 'Leclerc' },
          { id: 'norris',      name: 'Lando Norris',        searchTerm: 'Lando Norris' },
          { id: 'piastri',     name: 'Oscar Piastri',       searchTerm: 'Piastri' },
          { id: 'sainz',       name: 'Carlos Sainz',        searchTerm: 'Carlos Sainz' },
          { id: 'alonso',      name: 'Fernando Alonso',     searchTerm: 'Fernando Alonso' },
          { id: 'russell',     name: 'George Russell',      searchTerm: 'George Russell' },
          { id: 'perez',       name: 'Sergio Perez',        searchTerm: 'Sergio Perez' },
          { id: 'hulkenberg',  name: 'Nico Hulkenberg',     searchTerm: 'Hulkenberg' },
          { id: 'albon',       name: 'Alexander Albon',     searchTerm: 'Alexander Albon' },
          { id: 'tsunoda',     name: 'Yuki Tsunoda',        searchTerm: 'Yuki Tsunoda' },
          { id: 'stroll',      name: 'Lance Stroll',        searchTerm: 'Lance Stroll' },
          { id: 'gasly',       name: 'Pierre Gasly',        searchTerm: 'Pierre Gasly' },
          { id: 'ocon',        name: 'Esteban Ocon',        searchTerm: 'Esteban Ocon' },
          { id: 'bottas',      name: 'Valtteri Bottas',     searchTerm: 'Valtteri Bottas' },
          { id: 'zhou',        name: 'Guanyu Zhou',         searchTerm: 'Guanyu Zhou' },
          { id: 'magnussen',   name: 'Kevin Magnussen',     searchTerm: 'Kevin Magnussen' },
          { id: 'lawson',      name: 'Liam Lawson',         searchTerm: 'Liam Lawson' },
          { id: 'bearman',     name: 'Oliver Bearman',      searchTerm: 'Oliver Bearman' },
        ],
      },
      {
        label: 'Constructors',
        items: [
          { id: 'redbull',      name: 'Red Bull Racing',   searchTerm: 'Red Bull Racing' },
          { id: 'mercedes',     name: 'Mercedes',          searchTerm: 'Mercedes F1' },
          { id: 'ferrari',      name: 'Ferrari',           searchTerm: 'Ferrari F1' },
          { id: 'mclaren',      name: 'McLaren',           searchTerm: 'McLaren F1' },
          { id: 'astonmartin',  name: 'Aston Martin',      searchTerm: 'Aston Martin F1' },
          { id: 'alpine',       name: 'Alpine',            searchTerm: 'Alpine F1' },
          { id: 'williams',     name: 'Williams',          searchTerm: 'Williams F1' },
          { id: 'haas',         name: 'Haas',              searchTerm: 'Haas F1' },
        ],
      },
    ],
  },

  'ncaa-football': {
    groups: [
      {
        label: 'Programs',
        items: [
          { id: 'alabama',    name: 'Alabama',     searchTerm: 'Alabama football' },
          { id: 'ohiostate',  name: 'Ohio State',  searchTerm: 'Ohio State football' },
          { id: 'georgia',    name: 'Georgia',     searchTerm: 'Georgia Bulldogs' },
          { id: 'michigan',   name: 'Michigan',    searchTerm: 'Michigan football' },
          { id: 'clemson',    name: 'Clemson',     searchTerm: 'Clemson' },
          { id: 'lsu',        name: 'LSU',         searchTerm: 'LSU football' },
          { id: 'oklahoma',   name: 'Oklahoma',    searchTerm: 'Oklahoma Sooners' },
          { id: 'notredame',  name: 'Notre Dame',  searchTerm: 'Notre Dame football' },
          { id: 'pennstate',  name: 'Penn State',  searchTerm: 'Penn State football' },
          { id: 'usc',        name: 'USC',         searchTerm: 'USC football' },
          { id: 'texas',      name: 'Texas',       searchTerm: 'Texas Longhorns' },
          { id: 'florida',    name: 'Florida',     searchTerm: 'Florida Gators' },
          { id: 'oregonafc',  name: 'Oregon',      searchTerm: 'Oregon Ducks football' },
          { id: 'washington', name: 'Washington',  searchTerm: 'Washington Huskies football' },
          { id: 'miamifla',   name: 'Miami',       searchTerm: 'Miami Hurricanes football' },
          { id: 'florida-st', name: 'Florida State', searchTerm: 'Florida State football' },
        ],
      },
    ],
  },

  ufc: {
    groups: [
      {
        label: 'Fighters',
        items: [
          { id: 'jonjones',     name: 'Jon Jones',              searchTerm: 'Jon Jones UFC' },
          { id: 'makhachev',    name: 'Islam Makhachev',        searchTerm: 'Makhachev' },
          { id: 'volkanovski',  name: 'Alexander Volkanovski',  searchTerm: 'Volkanovski' },
          { id: 'omalley',      name: "Sean O'Malley",          searchTerm: "Sean O'Malley" },
          { id: 'apereira',     name: 'Alex Pereira',           searchTerm: 'Alex Pereira' },
          { id: 'edwards',      name: 'Leon Edwards',           searchTerm: 'Leon Edwards' },
          { id: 'mcgregor',     name: 'Conor McGregor',         searchTerm: 'McGregor' },
          { id: 'topuria',      name: 'Ilia Topuria',           searchTerm: 'Topuria' },
          { id: 'duplessis',    name: 'Dricus du Plessis',      searchTerm: 'du Plessis' },
          { id: 'aspinall',     name: 'Tom Aspinall',           searchTerm: 'Tom Aspinall' },
          { id: 'adesanya',     name: 'Israel Adesanya',        searchTerm: 'Adesanya' },
          { id: 'coliveira',    name: 'Charles Oliveira',       searchTerm: 'Charles Oliveira' },
          { id: 'prochazkaj',   name: 'Jiri Prochazka',         searchTerm: 'Jiri Prochazka' },
          { id: 'holloway',     name: 'Max Holloway',           searchTerm: 'Max Holloway' },
          { id: 'ngannou',      name: 'Francis Ngannou',        searchTerm: 'Francis Ngannou' },
          { id: 'poirier',      name: 'Dustin Poirier',         searchTerm: 'Dustin Poirier' },
          { id: 'gaethje',      name: 'Justin Gaethje',         searchTerm: 'Justin Gaethje' },
          { id: 'chandler',     name: 'Michael Chandler',       searchTerm: 'Michael Chandler' },
          { id: 'strickland',   name: 'Sean Strickland',        searchTerm: 'Sean Strickland' },
          { id: 'ankalaev',     name: 'Magomed Ankalaev',       searchTerm: 'Magomed Ankalaev' },
          { id: 'blachowicz',   name: 'Jan Blachowicz',         searchTerm: 'Jan Blachowicz' },
          { id: 'chimaev',      name: 'Khamzat Chimaev',        searchTerm: 'Khamzat Chimaev' },
          { id: 'vettori',      name: 'Marvin Vettori',         searchTerm: 'Marvin Vettori' },
          { id: 'belal',        name: 'Belal Muhammad',         searchTerm: 'Belal Muhammad' },
          { id: 'shevchenko',   name: 'Valentina Shevchenko',   searchTerm: 'Valentina Shevchenko' },
          { id: 'namajunas',    name: 'Rose Namajunas',         searchTerm: 'Rose Namajunas' },
          { id: 'nunes',        name: 'Amanda Nunes',           searchTerm: 'Amanda Nunes' },
          { id: 'grasso',       name: 'Alexa Grasso',           searchTerm: 'Alexa Grasso' },
          { id: 'jedrzejczyk',  name: 'Joanna Jedrzejczyk',    searchTerm: 'Joanna Jedrzejczyk' },
          { id: 'aldana',       name: 'Irene Aldana',           searchTerm: 'Irene Aldana' },
        ],
      },
    ],
  },

};

/** Flatten all groups for a sport into a single item list (for search-term lookups). */
export function allItemsForSport(sportId: SportId) {
  return SPORT_TEAMS[sportId]?.groups.flatMap((g) => g.items) ?? [];
}

// Group labels whose items are individual people rather than teams/clubs —
// the schedule lookup resolves these via player search (player → their team).
const PLAYER_GROUP_LABELS = new Set(["Men's ATP", "Women's WTA", 'Players', 'Drivers', 'Fighters']);

export interface FollowedEntity {
  kind: 'team' | 'player';
  sport: SportId;
  name: string;
}

/** All selected picks across sports, tagged team/player for schedule lookups. */
export function followedEntities(teams: Partial<Record<SportId, string[]>>): FollowedEntity[] {
  const out: FollowedEntity[] = [];
  for (const [sportId, ids] of Object.entries(teams)) {
    if (!ids?.length) continue;
    for (const group of SPORT_TEAMS[sportId as SportId]?.groups ?? []) {
      const kind = PLAYER_GROUP_LABELS.has(group.label) ? 'player' : 'team';
      for (const item of group.items) {
        if (ids.includes(item.id)) out.push({ kind, sport: sportId as SportId, name: item.name });
      }
    }
  }
  return out;
}
